sudo: false

language: node_js

cache:
  directories:
    - node_modules

node_js:
  - "0.12"
  - "4"
  - "6"
  - "7"

script: npm run coverage-lcov

after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
